config = {'train_data_path':['./data/luna16/subset0/',
                             './data/luna16/subset1/',
                             './data/luna16/subset2/',
                             './data/luna16/subset3/',
                             './data/luna16/subset4/',
                             './data/luna16/subset5/',
                             './data/luna16/subset6/',
                             './data/luna16/subset7/',
                             './data/luna16/subset8/'],
          'val_data_path':['./data/luna16/subset9/'], 
          'test_data_path':['./data/luna16/subset9/'], 
          
          'train_preprocess_result_path':'./data/luna16/preprocess/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'./data/luna16/preprocess/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'./data/luna16/preprocess/',
          
          'train_annos_path':'./data/luna16/csv/annotations.csv',
          'val_annos_path':'./data/luna16/csv/annotations.csv',
          'test_annos_path':'./data/luna16/csv/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',

          'luna_segment':'./data/luna16/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':'./data/luna16/preprocess/',
          'luna_data':'./data/luna16/',
          'luna_label':'./data/luna16/csv/annotations.csv'
         } 
